[package]
name = "armdis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yaxpeax-bench"
path = "src/main.rs"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = true

[dependencies]
yaxpeax-arm = { version = "0.4.0" }
yaxpeax-arch = "*"

[features]
formatter = []
